In [7]:
import pandas as pd

In [8]:
url = 'https://s3.eu-west-1.amazonaws.com/data.cyber.org.il/virtual_courses/introdata/colab/spotify_tracks1.csv'
artists = pd.read_csv(url)

In [9]:
artists.dtypes

name                 object
artists              object
id_artists           object
release_year          int64
popularity            int64
duration_minutes    float64
key                  object
mode                  int64
explicit              int64
danceability        float64
energy              float64
loudness            float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
dtype: object

In [10]:
series_of_numbers=pd.Series([9,0,2,1,0])
series_of_strings=pd.Series(['this','is','a','Pandas','series'])

In [11]:
print(series_of_numbers)

0    9
1    0
2    2
3    1
4    0
dtype: int64


In [12]:
sorted_series=series_of_strings.sort_values()

In [13]:
series_of_strings.loc[0]


'this'

In [14]:
sorted_series.loc[0]

'this'

In [15]:
sorted_series.iloc[0]

'Pandas'

In [16]:
sorted_series.iloc[2:6]

1        is
4    series
0      this
dtype: object

In [17]:
artists_by_popularity=artists.sort_values('popularity',ascending=False)

In [18]:
artists_by_popularity.head()

name   
87286  Peaches (feat. Daniel Caesar & Giveon)  \
87287                         drivers license   
87288                  Astronaut In The Ocean   
86367                         Save Your Tears   
86368                               telepatía   

                                      artists              id_artists   
87286  Justin Bieber & Daniel Caesar & Giveon  1uNFoZAHBGtllmzznpCI3s  \
87287                          Olivia Rodrigo  1McMsnEElThX1knmY4oliG   
87288                             Masked Wolf  1uU7g3DNSbsu0QjSEqZtEd   
86367                              The Weeknd  1Xyo4u8uXC1ZmMpatF05PJ   
86368                              Kali Uchis  1U1el3k54VvEUzo3ybLPlM   

       release_year  popularity  duration_minutes    key  mode  explicit   
87286          2021         100          3.301367     Do     1         1  \
87287          2021          99          4.033567  Si(b)     1         1   
87288          2021          98          2.213000     Mi     0         0   
86367          2020          97          3.593783     Do     1         1   
86368          2020          97          2.669850     Si     0         0   

       danceability  energy  loudness  speechiness  acousticness   
87286         0.677   0.696    -6.181       0.1190        0.3210  \
87287         0.585   0.436    -8.761       0.0601        0.7210   
87288         0.778   0.695    -6.865       0.0913        0.1750   
86367         0.680   0.826    -5.487       0.0309        0.0212   
86368         0.653   0.524    -9.016       0.0502        0.1120   

       instrumentalness  liveness  valence    tempo  
87286          0.000000     0.420    0.464   90.030  
87287          0.000013     0.105    0.132  143.874  
87288          0.000000     0.150    0.472  149.996  
86367          0.000012     0.543    0.644  118.051  
86368          0.000000     0.203    0.553   83.970

In [19]:
artists_by_popularity=artists.sort_values(['popularity','id_artists'],ascending=False)

In [20]:
artists_by_popularity.head(8)

name   
87286  Peaches (feat. Daniel Caesar & Giveon)  \
87287                         drivers license   
87288                  Astronaut In The Ocean   
86367                         Save Your Tears   
86368                               telepatía   
86369                         Blinding Lights   
87289                     Leave The Door Open   
86370                            The Business   

                                        artists              id_artists   
87286    Justin Bieber & Daniel Caesar & Giveon  1uNFoZAHBGtllmzznpCI3s  \
87287                            Olivia Rodrigo  1McMsnEElThX1knmY4oliG   
87288                               Masked Wolf  1uU7g3DNSbsu0QjSEqZtEd   
86367                                The Weeknd  1Xyo4u8uXC1ZmMpatF05PJ   
86368                                Kali Uchis  1U1el3k54VvEUzo3ybLPlM   
86369                                The Weeknd  1Xyo4u8uXC1ZmMpatF05PJ   
87289  Bruno Mars & Anderson .Paak & Silk Sonic  0du5cEVh5yTK9QJze8zA0C   
86370                                    Tiësto  2o5jDhtHVPhrJdv3cEQ99Z   

       release_year  popularity  duration_minutes    key  mode  explicit   
87286          2021         100          3.301367     Do     1         1  \
87287          2021          99          4.033567  Si(b)     1         1   
87288          2021          98          2.213000     Mi     0         0   
86367          2020          97          3.593783     Do     1         1   
86368          2020          97          2.669850     Si     0         0   
86369          2020          96          3.334000  Re(b)     1         0   
87289          2021          96          4.034933     Fa     1         0   
86370          2020          95          2.733333  La(b)     0         0   

       danceability  energy  loudness  speechiness  acousticness   
87286         0.677   0.696    -6.181       0.1190       0.32100  \
87287         0.585   0.436    -8.761       0.0601       0.72100   
87288         0.778   0.695    -6.865       0.0913       0.17500   
86367         0.680   0.826    -5.487       0.0309       0.02120   
86368         0.653   0.524    -9.016       0.0502       0.11200   
86369         0.514   0.730    -5.934       0.0598       0.00146   
87289         0.586   0.616    -7.964       0.0324       0.18200   
86370         0.798   0.620    -7.079       0.2320       0.41400   

       instrumentalness  liveness  valence    tempo  
87286          0.000000    0.4200    0.464   90.030  
87287          0.000013    0.1050    0.132  143.874  
87288          0.000000    0.1500    0.472  149.996  
86367          0.000012    0.5430    0.644  118.051  
86368          0.000000    0.2030    0.553   83.970  
86369          0.000095    0.0897    0.334  171.005  
87289          0.000000    0.0927    0.719  148.088  
86370          0.019200    0.1120    0.235  120.031

In [21]:
artists_by_popularity.iloc[0:9,:]

name   
87286  Peaches (feat. Daniel Caesar & Giveon)  \
87287                         drivers license   
87288                  Astronaut In The Ocean   
86367                         Save Your Tears   
86368                               telepatía   
86369                         Blinding Lights   
87289                     Leave The Door Open   
86370                            The Business   
86375                                 Bandido   

                                        artists              id_artists   
87286    Justin Bieber & Daniel Caesar & Giveon  1uNFoZAHBGtllmzznpCI3s  \
87287                            Olivia Rodrigo  1McMsnEElThX1knmY4oliG   
87288                               Masked Wolf  1uU7g3DNSbsu0QjSEqZtEd   
86367                                The Weeknd  1Xyo4u8uXC1ZmMpatF05PJ   
86368                                Kali Uchis  1U1el3k54VvEUzo3ybLPlM   
86369                                The Weeknd  1Xyo4u8uXC1ZmMpatF05PJ   
87289  Bruno Mars & Anderson .Paak & Silk Sonic  0du5cEVh5yTK9QJze8zA0C   
86370                                    Tiësto  2o5jDhtHVPhrJdv3cEQ99Z   
86375                        Myke Towers & Juhn  7iK8PXO48WeuP03g8YR51W   

       release_year  popularity  duration_minutes    key  mode  explicit   
87286          2021         100          3.301367     Do     1         1  \
87287          2021          99          4.033567  Si(b)     1         1   
87288          2021          98          2.213000     Mi     0         0   
86367          2020          97          3.593783     Do     1         1   
86368          2020          97          2.669850     Si     0         0   
86369          2020          96          3.334000  Re(b)     1         0   
87289          2021          96          4.034933     Fa     1         0   
86370          2020          95          2.733333  La(b)     0         0   
86375          2020          94          3.880883  La(b)     1         0   

       danceability  energy  loudness  speechiness  acousticness   
87286         0.677   0.696    -6.181       0.1190       0.32100  \
87287         0.585   0.436    -8.761       0.0601       0.72100   
87288         0.778   0.695    -6.865       0.0913       0.17500   
86367         0.680   0.826    -5.487       0.0309       0.02120   
86368         0.653   0.524    -9.016       0.0502       0.11200   
86369         0.514   0.730    -5.934       0.0598       0.00146   
87289         0.586   0.616    -7.964       0.0324       0.18200   
86370         0.798   0.620    -7.079       0.2320       0.41400   
86375         0.713   0.617    -4.637       0.0887       0.12200   

       instrumentalness  liveness  valence    tempo  
87286          0.000000    0.4200    0.464   90.030  
87287          0.000013    0.1050    0.132  143.874  
87288          0.000000    0.1500    0.472  149.996  
86367          0.000012    0.5430    0.644  118.051  
86368          0.000000    0.2030    0.553   83.970  
86369          0.000095    0.0897    0.334  171.005  
87289          0.000000    0.0927    0.719  148.088  
86370          0.019200    0.1120    0.235  120.031  
86375          0.000000    0.0962    0.682  168.021

In [22]:
artists_by_popularity[['artists','popularity','id_artists']]

artists  popularity   
87286   Justin Bieber & Daniel Caesar & Giveon         100  \
87287                           Olivia Rodrigo          99   
87288                              Masked Wolf          98   
86367                               The Weeknd          97   
86368                               Kali Uchis          97   
...                                        ...         ...   
316493                       Vyacheslav Sketch           0   
456886           Rastragayak Shantilal B. Shah           0   
456933           Rastragayak Shantilal B. Shah           0   
74511                                 Bletzung           0   
161575                            Motion Drive           0   

                    id_artists  
87286   1uNFoZAHBGtllmzznpCI3s  
87287   1McMsnEElThX1knmY4oliG  
87288   1uU7g3DNSbsu0QjSEqZtEd  
86367   1Xyo4u8uXC1ZmMpatF05PJ  
86368   1U1el3k54VvEUzo3ybLPlM  
...                        ...  
316493  006ZADyabxpgKqMmh8W2yz  
456886  004Da0eAbekHrjGgSQhKHZ  
456933  004Da0eAbekHrjGgSQhKHZ  
74511   001zCqILBoELQX6teUKKDf  
161575  0001wHqxbF2YYRQxGdbyER  

[521260 rows x 3 columns]

In [23]:
artists_by_popularity.loc[:,['artists','popularity','id_artists']]

artists  popularity   
87286   Justin Bieber & Daniel Caesar & Giveon         100  \
87287                           Olivia Rodrigo          99   
87288                              Masked Wolf          98   
86367                               The Weeknd          97   
86368                               Kali Uchis          97   
...                                        ...         ...   
316493                       Vyacheslav Sketch           0   
456886           Rastragayak Shantilal B. Shah           0   
456933           Rastragayak Shantilal B. Shah           0   
74511                                 Bletzung           0   
161575                            Motion Drive           0   

                    id_artists  
87286   1uNFoZAHBGtllmzznpCI3s  
87287   1McMsnEElThX1knmY4oliG  
87288   1uU7g3DNSbsu0QjSEqZtEd  
86367   1Xyo4u8uXC1ZmMpatF05PJ  
86368   1U1el3k54VvEUzo3ybLPlM  
...                        ...  
316493  006ZADyabxpgKqMmh8W2yz  
456886  004Da0eAbekHrjGgSQhKHZ  
456933  004Da0eAbekHrjGgSQhKHZ  
74511   001zCqILBoELQX6teUKKDf  
161575  0001wHqxbF2YYRQxGdbyER  

[521260 rows x 3 columns]

In [24]:
artists.columns

Index(['name', 'artists', 'id_artists', 'release_year', 'popularity',
       'duration_minutes', 'key', 'mode', 'explicit', 'danceability', 'energy',
       'loudness', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo'],
      dtype='object')

In [25]:
artists_by_popularity.iloc[10:20,[1,4,2]]

artists  popularity   
85486                               Doja Cat          94  \
86372                                 Giveon          94   
86373                          The Kid LAROI          94   
87290  Los Legendarios & Wisin & Jhay Cortez          94   
86379                                    SZA          93   
86377                    Bad Bunny & ROSALÍA          93   
85487                           Harry Styles          92   
86382                          Ariana Grande          92   
87292  Rochy RD & Myke Towers & Nicki Nicole          92   
86380                Bad Bunny & Jhay Cortez          92   

                   id_artists  
85486  5cj0lLjcoR7YOSnhnX0Po5  
86372  4fxd5Ee7UefO4CUXgwJ7IP  
86373  2tIP7SsRs7vjIcLrU85W8J  
87290  0n6sKrG0xKAf8xmdqeNGke  
86379  7tYKF4w9nC0nq9CsPZTHyP  
86377  4q3ewBCX7sLwd24euuV69X  
85487  6KImCVD70vtIoJWnq6nGn3  
86382  66CXWjxzNUsdJxJ2JdwvnR  
87292  4riOEaOW5hCeqomFDBk0aP  
86380  4q3ewBCX7sLwd24euuV69X

In [26]:
artists_by_popularity[['artists','popularity','id_artists']].iloc[:10]

artists  popularity   
87286             Justin Bieber & Daniel Caesar & Giveon         100  \
87287                                     Olivia Rodrigo          99   
87288                                        Masked Wolf          98   
86367                                         The Weeknd          97   
86368                                         Kali Uchis          97   
86369                                         The Weeknd          96   
87289           Bruno Mars & Anderson .Paak & Silk Sonic          96   
86370                                             Tiësto          95   
86375                                 Myke Towers & Juhn          94   
87291  Riton & Nightcrawlers & Mufasa & Hypeman & Dop...          94   

                   id_artists  
87286  1uNFoZAHBGtllmzznpCI3s  
87287  1McMsnEElThX1knmY4oliG  
87288  1uU7g3DNSbsu0QjSEqZtEd  
86367  1Xyo4u8uXC1ZmMpatF05PJ  
86368  1U1el3k54VvEUzo3ybLPlM  
86369  1Xyo4u8uXC1ZmMpatF05PJ  
87289  0du5cEVh5yTK9QJze8zA0C  
86370  2o5jDhtHVPhrJdv3cEQ99Z  
86375  7iK8PXO48WeuP03g8YR51W  
87291  7i9j813KFoSBMldGqlh2Z1

עד עכשיו עבדנו עם pandas על אובייקטים מסוג Series. ראינו שהם מכילים רצף של ערכים, למשל רצף של מספרים או רצף של מחרוזות, ונחשפנו לעוד כמה תכונות מעניינות שלהם.

אנחנו כבר מכירים סוג אחר של רצף – רשימה.

ניזכר בהבדלים בין רשימה לסדרה:

נתחיל ביצירת רשימה וסדרה.
עבור שתיהן בחרנו, לצורך הדוגמה, תשעה מספרים ראשוניים הראשונים:

In [27]:
list1 = [2, 3, 5, 7, 11, 13, 17, 19, 23]
type(list1)

list

In [28]:
series1 = pd.Series([2, 3, 5, 7, 11, 13, 17, 19, 23])
type(series1)

pandas.core.series.Series

In [29]:
print(list1)

[2, 3, 5, 7, 11, 13, 17, 19, 23]


In [30]:
print(series1)

0     2
1     3
2     5
3     7
4    11
5    13
6    17
7    19
8    23
dtype: int64


שליפה מרשימה אפשר לבצע אך ורק על סמך המיקום ברשימה, בעזרת הסוגריים המרובעים:

In [31]:
print(list1[0])
print(list1[-1])
print(list1[4:7])

2
23
[11, 13, 17]


בשליפה מסדרה עלינו להשתמש במתודה iloc, ממש כמו שהשתמשנו בה ב-pandas. חוץ מהצורך להשתמש בשמה של המתודה, אין הרבה הבדל, והשליפות פועלות באותו אופן:

In [32]:
print(series1.iloc[0])
print(series1.iloc[-1])
print(series1.iloc[4:7])

2
23
4    11
5    13
6    17
dtype: int64


עד כה נראה כי שליפה בסדרה די דומה לשליפה ברשימה, וההבדל המהותי הוא בטור האינדקסים בהדפסה של סדרה, טור שכאמור לא קיים בהדפסת רשימה.
 טור האינדקס מציג שם לכל תא. אפשר גם ליצור אינדקס דרך הזנה של רצף ערכים לתכונה 'אינדקס' (חשוב להקפיד שהרצף יהיה זהה באורכו למספר האיברים בסדרה):

In [33]:
series1.index = [0, 1, 10, 11, 100, 101, 110, 111, 1000]

כך אפשר להשתמש במתודה המיוחדת loc, 
ששולפת את האיבר לפי האינדקס. השמות שזה עתה הגדרנו לכל אחד מהתאים בסדרה משמשים כמפתחות.
הנה דוגמה לשתי אפשרויות לשליפה בעזרת loc: 
שתי השורות הראשונות מציגות שליפה של איבר בודד, ובשורה השלישית שליפה של טווח:

In [34]:
print(series1.loc[0])
print(series1.loc[1000])
print(series1.loc[100:110])

2
23
100    11
101    13
110    17
dtype: int64


שליפה לפי מיקום דומה לשליפה מרשימה ושליפה לפי אינדקס דומה לשליפה ממילון, ולכן אפשר לומר שהסדרה מתנהגת כמו 'גם רשימה וגם מילון'.1
לסדרה יש גם מגבלה שבמילון וברשימה דווקא לא קיימת, והיא שבסדרה, מהרגע שנוצרה, אי אפשר להוסיף איברים או למחוק אותם.2

נזכיר כמה קל ופשוט להוסיף איברים לרשימה ולמחוק:

In [35]:
list1.append(29)
print(list1)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [36]:
list1.pop()
print(list1)

[2, 3, 5, 7, 11, 13, 17, 19, 23]


גם לסדרה יש את הדרכים שלה להפוך את החיים לקלים יותר, למשל היא מאפשרת לבצע בקלות פעולות חשבון רגילות על כל האיברים בסדרה:

In [37]:
series1 / 2


0        1.0
1        1.5
10       2.5
11       3.5
100      5.5
101      6.5
110      8.5
111      9.5
1000    11.5
dtype: float64

אם בכל זאת תרצו לבצע פעולות חשבון ברשימה, תזדקקו לקצת עזרה ממנגנון list comprehension:

In [38]:
[m/2 for m in list1]

[1.0, 1.5, 2.5, 3.5, 5.5, 6.5, 8.5, 9.5, 11.5]

Creating a numpy array:
בדומה לרשימה ולסדרה שיצרנו קודם, נייצר כעת מערך. 
וכפי שיצירת סדרה נעשית בעזרת פונקציה מתוך pandas,
יצירת מערך נעשית בעזרת פונקציה מתוך numpy.

In [39]:
import numpy as np

In [40]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23])
type(array1)

numpy.ndarray

In [41]:
print(array1)

[ 2  3  5  7 11 13 17 19 23]


In [42]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [43]:
array2=np.array(list1)
array2

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

אם הנתונים שלנו שמורים בסדרה (ולא ברשימה) ואנחנו רוצים ליצור מהם מערך, נוכל להשתמש בתכונה values, הממירה סדרה למערך numpy:



In [44]:
series1.values

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23], dtype=int64)

In [45]:
type(series1.values)


numpy.ndarray

חיבור מערכים

In [47]:
beatles_songs_per_year_1963_to_1970 = np.array([31, 35, 33, 16, 24, 34, 26, 11])
simon_and_garfunkel_songs_per_year_1963_to_1970 = np.array([0, 12, 0, 27, 1, 10, 0, 13])
total_songs = beatles_songs_per_year_1963_to_1970 + simon_and_garfunkel_songs_per_year_1963_to_1970
total_songs

array([31, 47, 33, 43, 25, 44, 26, 24])

חיסור מערכים

In [48]:
beatles_songs_per_year_1963_to_1970 - simon_and_garfunkel_songs_per_year_1963_to_1970

array([ 31,  23,  33, -11,  23,  24,  26,  -2])

חלק יחסי מתוך הסך הכל

In [50]:
simon_and_garfunkel_proportion = simon_and_garfunkel_songs_per_year_1963_to_1970 / total_songs
simon_and_garfunkel_proportion

array([0.        , 0.25531915, 0.        , 0.62790698, 0.04      ,
       0.22727273, 0.        , 0.54166667])

In [51]:
simon_and_garfunkel_percent = simon_and_garfunkel_proportion * 100
simon_and_garfunkel_percent

array([ 0.        , 25.53191489,  0.        , 62.79069767,  4.        ,
       22.72727273,  0.        , 54.16666667])

In [52]:
round(simon_and_garfunkel_percent[1])

26

In [53]:
np.round(simon_and_garfunkel_percent)

array([ 0., 26.,  0., 63.,  4., 23.,  0., 54.])